image: python:2.7

stages:
 - test

before_script:
  - "pip install -U platformio"
  -  platformio lib -g install "FastLED"

job:
  stage: test
  script: "platformio ci --board=uno"
  variables: {PLATFORMIO_CI_SRC: "src/main.cpp"}
  artifacts:
    paths:
      - /builds/srchip/miku_soundboard/.pioenvs/uno/firmware.elf
